#20265: Adjust grid usage in matmul test and add checks for validate (#20569)
### Ticket
Link to Github Issue #20265 

Updated files to fix a failure on TG llama tests.

### Problem description
A test used a different grid for the input tensor and the matmul
computation.

### What's changed
- update the test to use the same grid and make the grid fit on any WH
and BH
- add validation to check that the input tensor grid is within the
computation grid (only for 2D multicast and 1D non-gather multicast)

### Testing

Verified locally that if grid for config is transposed the error occurs:
```
E       RuntimeError: TT_FATAL @ /localdev/bbradel/tt-metal/ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:1400: range.contains(shard_grid)
E       info:
E       Tensor shard spec grid must be within config grid! Shard grid: {[(x=0,y=0) - (x=5,y=2)], [(x=0,y=3) - (x=3,y=3)]}, Config grid: [(x=0,y=0) - (x=4,y=7)]
```

Verified on a galaxy that
```
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_matmul_1d_gather_in0.py::test_matmul_1d_ring_llama_perf -k qkv
```
failed with changes in the preceding PR and passes with the current PR.

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/14405799977
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI passes (if applicable) N/A
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable) N/A
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable) N/A
- [ ] **(For models and ops writers)** Full [new models
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml)
CI passes (if applicable) N/A
- [ ] New/Existing tests provide coverage for changes

TG Tests:
- unit failed for other reasons
https://github.com/tenstorrent/tt-metal/actions/runs/14405773890/job/40402166507
AssertionError: Expected 32 devices, got 4
- frequent
https://github.com/tenstorrent/tt-metal/actions/runs/14405777668/job/40402166297
The action 'Run unit regression tests' has timed out after 45 minutes.
- demo llama test passes
https://github.com/tenstorrent/tt-metal/actions/runs/14405769252