[skip ci] #0: Fix produce data crash when testcase is missing properties block (#17499)
### Ticket
Link to Github Issue

### Problem description
Testcase may not have a `<properties>` block returned by pytest testcase
xml if the test job was terminated (e.g. by timeout). This block is used
to read test start and end timestamps.

Currently the script expects that properties blocks must exist and early
exits which fails the produce_data workflow.

https://github.com/tenstorrent/tt-metal/actions/runs/13115705029/job/36589339402
```
Traceback (most recent call last):
  File ".github/scripts/data_analysis/create_pipeline_json.py", line 15, in <module>
    pipeline = create_cicd_json_for_data_analysis(
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/cicd.py", line 69, in create_cicd_json_for_data_analysis
    tests = get_tests_from_test_report_path(test_report_path)
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/github/workflows.py", line 231, in get_tests_from_test_report_path
    tests.append(get_pydantic_test(testcase))
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/github/workflows.py", line 148, in get_pydantic_test_from_pytest_testcase_
    properties = junit_xml_utils.get_pytest_testcase_properties(testcase)
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/junit_xml_utils.py", line 55, in get_pytest_testcase_properties
    assert properties_block is not None
AssertionError
Error: Process completed with exit code 1.
```

### What's changed
If the `<properties>` block doesn't exist, log a warning and use the
default timestamp instead.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new
models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml)
tests passes
- [x] New/Existing tests provide coverage for changes

https://github.com/tenstorrent/tt-metal/actions/runs/13117840832/job/36596401546#step:9:1721
Reupload of same pipeline test run on local branch w/ fix