Revert "Llama TG: support persistent prefill traces " (#20359)
Reverts tenstorrent/tt-metal#20327
breaks tg quick test

```
            # Always print perf at every iteration
            logger.info(
                f"Iteration {iteration}: {1000*iteration_time:.0f}ms @ {tokens_per_second_per_user:.1f} tok/s/user ({batch_size*tokens_per_second_per_user:.1f} tok/s throughput)"
            )
            tsu_threshold = 128 if layers == 1 else 28
            if not stress_test:
>               assert tokens_per_second_per_user > tsu_threshold, "Throughput is less than 28 tokens per second per user"
E               AssertionError: Throughput is less than 28 tokens per second per user
E               assert 69.80036611749043 > 128

models/demos/llama3_subdevices/demo/demo_decode.py:458: AssertionError
```


https://github.com/tenstorrent/tt-metal/actions/runs/14336831841/job/40187403788#step:5:2580